import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
const inter = Inter({ subsets: ['latin'] })
import { Toaster } from "@/components/ui/toaster"

export const metadata: Metadata = {
  title: 'Süslü Crm',
  description: 'Generated by Süslü',
}
import { ClerkProvider } from '@clerk/nextjs'
import { Providers } from '@/components/provider/provider'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
<ClerkProvider>
    <html lang="en" suppressHydrationWarning>
        <body className={`${inter.className}`} suppressHydrationWarning>
        <Providers>
          {children}
          <Toaster />
        </Providers>
        </body>
    </html>
</ClerkProvider>
  )
}
